spring.datasource.url=jdbc:cloudspanner://localhost:9010/projects/test-project/instances/test-instance/databases/testdb?usePlainText=true
spring.datasource.driver-class-name=com.google.cloud.spanner.jdbc.JdbcDriver
spring.jpa.database-platform=com.google.cloud.spanner.hibernate.SpannerDialect
spring.jpa.properties.hibernate.dialect=com.google.cloud.spanner.hibernate.SpannerDialect
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/spanner/schema.sql
spring.sql.init.data-locations=classpath:db/spanner/data.sql
spring.jpa.hibernate.ddl-auto=none
